create table `users` (`id` int unsigned not null auto_increment primary key, `name` varchar(255) not null, `email` varchar(255) not null, `password` varchar(255) not null, `remember_token` varchar(100) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate utf8mb4_unicode_ci;
alter table `users` add unique `users_email_unique`(`email`);
create table `password_resets` (`email` varchar(255) not null, `token` varchar(255) not null, `created_at` timestamp null) default character set utf8mb4 collate utf8mb4_unicode_ci;
alter table `password_resets` add index `password_resets_email_index`(`email`);
create table `hrefs` (`id` int unsigned not null auto_increment primary key, `parent_id` int unsigned not null, `user_id` int unsigned not null, `date_added` timestamp null, `index` int unsigned not null default '0', `visible` tinyint(1) not null default '1', `title` varchar(255) not null, `url` varchar(500) null, `created_by` int unsigned not null, `created_by_name` varchar(255) not null, `updated_by` int unsigned null, `updated_by_name` varchar(255) not null default '', `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate utf8mb4_unicode_ci;
alter table `hrefs` add constraint `hrefs_user_id_foreign` foreign key (`user_id`) references `users` (`id`);
alter table `hrefs` add constraint `hrefs_created_by_foreign` foreign key (`created_by`) references `users` (`id`) on delete no action;
alter table `hrefs` add constraint `hrefs_updated_by_foreign` foreign key (`updated_by`) references `users` (`id`) on delete no action;
alter table `hrefs` add index `hrefs_created_by_index`(`created_by`);
create table `tags` (`id` int unsigned not null auto_increment primary key, `tag` varchar(255) not null, `created_by` int unsigned not null, `created_by_name` varchar(255) not null, `updated_by` int unsigned null, `updated_by_name` varchar(255) not null default '', `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate utf8mb4_unicode_ci;
alter table `tags` add constraint `tags_created_by_foreign` foreign key (`created_by`) references `users` (`id`) on delete no action;
alter table `tags` add constraint `tags_updated_by_foreign` foreign key (`updated_by`) references `users` (`id`) on delete no action;
alter table `tags` add unique `tags_tag_unique`(`tag`);
alter table `tags` add index `tags_created_by_index`(`created_by`);
create table `href_tags` (`id` int unsigned not null auto_increment primary key, `href_id` int unsigned not null, `tag_id` int unsigned not null) default character set utf8mb4 collate utf8mb4_unicode_ci;
alter table `href_tags` add constraint `href_tags_href_id_foreign` foreign key (`href_id`) references `hrefs` (`id`);
alter table `href_tags` add constraint `href_tags_tag_id_foreign` foreign key (`tag_id`) references `tags` (`id`);
alter table `href_tags` add index `href_tags_href_id_index`(`href_id`);
alter table `href_tags` add index `href_tags_tag_id_index`(`tag_id`);
create table `categories` (`id` int unsigned not null auto_increment primary key, `title` varchar(255) not null, `created_by` int unsigned not null, `created_by_name` varchar(255) not null, `updated_by` int unsigned null, `updated_by_name` varchar(255) not null default '', `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate utf8mb4_unicode_ci;
alter table `categories` add constraint `categories_created_by_foreign` foreign key (`created_by`) references `users` (`id`) on delete no action;
alter table `categories` add constraint `categories_updated_by_foreign` foreign key (`updated_by`) references `users` (`id`) on delete no action;
alter table `categories` add index `categories_created_by_index`(`created_by`);
alter table `hrefs` add `category_id` int unsigned null;
alter table `hrefs` add constraint `hrefs_category_id_foreign` foreign key (`category_id`) references `categories` (`id`);
alter table `hrefs` add index `hrefs_category_id_index`(`category_id`);
